export const GET_MOVIES = "GET_MOVIES";
export const GET_SINGLE_MOVIE = "GET_SINGLE_MOVIE";
export const GET_MOVIE_CAST = "GET_MOVIE_CAST";
export const GET_MOVIE_RECOMMENDATIONS = "GET_MOVIE_RECOMMENDATIONS";
export const GET_CAST_DETAIL = "GET_CAST_DETAIL";
